apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularbuild
  labels:
    app: angularbuild
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angularbuild
  template:
    metadata:
      labels:
        app: angularbuild
    spec:
      containers:
      - name: angularbuild
        image: janmenjaya/angularbuild
        ports:
        - containerPort: 80  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0    

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: angularbuild
  name: angularbuild
  namespace: default
spec:
  clusterIP: 10.107.246.250
  clusterIPs:
  - 10.107.246.250
  ports:
  - nodePort: 32098
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: angularbuild
  sessionAffinity: None
  type: NodePort

